# Task 1: Working with a dataset with categorical features

## Step 1: Reading the data

In [30]:
# In this step we start by reading the csv file using panda library 
import pandas as pd

# Read the CSV file.
data_training = pd.read_csv("adult_training.CSV")
data_test = pd.read_csv("adult_test_data.CSV")

Xtrain = data_training.drop('target', axis=1)
Ytrain = data_training['target']

Xtest = data_test.drop('target',axis=1)
Ytest = data_test['target']


Step 1 objective is to read the data from the training and testing files. Unlike the previous assignemnt here we didnt split the data to training and testing because its already splitted in two files.

## Step 2:  Encoding the features as numbers.

In [2]:
dicts_for_my_training_data = Xtrain.to_dict('records')

In [3]:
dicts_for_my_test_data = Xtest.to_dict('records')

In [4]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Ytrain)
Ytrain=le.transform(Ytrain)

In manner to transform the data to numerical data we need to create dictionary vectors for the training and the test data. By using Pandas which includes a utility to convert a DataFrame into a list of dictionaries.

In [5]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer()
X_train_encoded = dv.fit_transform(dicts_for_my_training_data)
X_train_encoded

<32561x108 sparse matrix of type '<class 'numpy.float64'>'
	with 394963 stored elements in Compressed Sparse Row format>

The next step was to create the DictVectorizer and then fit the lables.

In [6]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Ytrain)
Ytrain=le.transform(Ytrain)
Ytrain

array([0, 0, 0, ..., 0, 1, 0])

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
clf1 = DecisionTreeClassifier()
cross_val_score(clf1, X_train_encoded, Ytrain).mean()

0.817726807771718

After that we have used the DecisionTreeClassifier and used the accuracy measure cross validation score to test the accuracy 
of the data  

Label Encoder

In [8]:
X_test_encoded = dv.transform(dicts_for_my_test_data)
X_test_encoded

<16281x108 sparse matrix of type '<class 'numpy.float64'>'
	with 227934 stored elements in Compressed Sparse Row format>

In [9]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Ytest)
Ytest=le.transform(Ytest)

Then we fitted the test data befoer using the pipline to combine all the previous steps 

## Step 3. Combining the steps.

In [10]:
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeClassifier
pipeline = make_pipeline(DictVectorizer(),DecisionTreeClassifier())
pipeline.fit(dicts_for_my_training_data, Ytrain)

Pipeline(steps=[('dictvectorizer', DictVectorizer()),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

To predict on new data it is as simple as calling the predict method and the preprocessing steps will be applied followed by the prediction.

In [11]:
Y_new = pipeline.predict(dicts_for_my_test_data)

In [12]:
# Cross-validation performance of test set with the predicted label
cross_val_score(clf1, X_test_encoded, Y_new).mean()

0.8219400059897449

In [13]:
# Cross-validation performance of test data usinf decision tree classifier
cross_val_score(clf1, X_test_encoded, Ytest).mean()

0.8094099346785868

# Task 2: Decision trees and random forests

 ## Underfitting and overfitting in decision tree classifiers. 

In [14]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Ytrain)
Ytrain=le.transform(Ytrain)
Ytrain

array([0, 0, 0, ..., 0, 1, 0])

In [15]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Ytest)
Ytest=le.transform(Ytest)
Ytest

array([0, 0, 1, ..., 0, 0, 1])

In [16]:
from sklearn.tree import DecisionTreeClassifier
clf2= DecisionTreeClassifier()
clf2.fit(X_train_encoded, Ytrain)


DecisionTreeClassifier()

In [24]:
from IPython.display import Image
from sklearn.externals.six import StringIO
from sklearn import tree
import pydotplus
dot_data=StringIO()
tree.export_graphviz(clf2,out_file=dot_data,filled=True,rounded=False,impurity=False)
graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png)

predict1=clf2.predict(X_train_encoded)
print(predict1)
predict2=clf2.predict(X_test_encoded)
print(predict2)

from sklearn.metrics import confusion_matrix
c1=confusion_matrix(Ytrain,predict1)
c1

total=sum(sum(c1))
#accuracy=(c1[0,0]+c1[1,1])/total
a1=c1[0,0]
a2=c1[1,1]
accuracy=(a1+a2)/total
print('Accuracy of training data:',accuracy)

c2=confusion_matrix(Ytest,predict2)
c2
total1=sum(sum(c2))
a3=c2[0,0]
a4=c2[1,1]
accuracy1=(a3+a4)/total1
print('Accuracy of test data:',accuracy1)



[0 0 0 ... 0 1 0]
[0 0 1 ... 1 0 0]
Accuracy of training data: 0.9999692884125181
Accuracy of test data: 0.8114980652294085


The accuracy of trianing set is almost 100%. and using the same model the test data accuracy is 81%. The model is good in trainning data and it is also good in test data.No problem with overfitting. Since we have nice predition on the future data set.

In [25]:
from sklearn.ensemble import RandomForestClassifier
clf3= RandomForestClassifier()
clf3.fit(X_train_encoded, Ytrain)

RandomForestClassifier()

In [26]:
from IPython.display import Image
from sklearn.externals.six import StringIO
from sklearn import tree
import pydotplus
dot_data=StringIO()
tree.export_graphviz(clf2,out_file=dot_data,filled=True,rounded=False,impurity=False)
graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png)

predict1=clf3.predict(X_train_encoded)
print(predict1)
predict2=clf3.predict(X_test_encoded)
print(predict2)

from sklearn.metrics import confusion_matrix
c1=confusion_matrix(Ytrain,predict1)
c1

total=sum(sum(c1))
#accuracy=(c1[0,0]+c1[1,1])/total
a1=c1[0,0]
a2=c1[1,1]
accuracy=(a1+a2)/total
print('Accuracy of training data:',accuracy)

c2=confusion_matrix(Ytest,predict2)
c2
total1=sum(sum(c2))
a3=c2[0,0]
a4=c2[1,1]
accuracy1=(a3+a4)/total1
print('Accuracy of test data:',accuracy1)


[0 0 0 ... 0 1 0]
[0 0 1 ... 1 0 1]
Accuracy of training data: 0.9999385768250361
Accuracy of test data: 0.8506234260794792


Using the defualt hyperparameter n_estimators parameter the accuracy of test data increases.


Let us try using different n_estimators values

In [27]:
from sklearn.ensemble import RandomForestClassifier
clf4= RandomForestClassifier(n_estimators=100,n_jobs = -1)
clf4.fit(X_train_encoded, Ytrain)

RandomForestClassifier(n_jobs=-1)

In [28]:
from IPython.display import Image
from sklearn.externals.six import StringIO
from sklearn import tree
import pydotplus
dot_data=StringIO()
tree.export_graphviz(clf2,out_file=dot_data,filled=True,rounded=False,impurity=False)
graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png)

predict1=clf4.predict(X_train_encoded)
print(predict1)
predict2=clf4.predict(X_test_encoded)
print(predict2)

from sklearn.metrics import confusion_matrix
c1=confusion_matrix(Ytrain,predict1)
c1

total=sum(sum(c1))
#accuracy=(c1[0,0]+c1[1,1])/total
a1=c1[0,0]
a2=c1[1,1]
accuracy=(a1+a2)/total
print('Accuracy of training data:',accuracy)

c2=confusion_matrix(Ytest,predict2)
c2
total1=sum(sum(c2))
a3=c2[0,0]
a4=c2[1,1]
accuracy1=(a3+a4)/total1
print('Accuracy of test data:',accuracy1)


[0 0 0 ... 0 1 0]
[0 0 0 ... 1 0 1]
Accuracy of training data: 0.9999692884125181
Accuracy of test data: 0.8516061666973773


What's the difference between the curve for a decision tree and for a random forest with an ensemble size of 1, and why do we see this difference?
Random forest is more use full in feature predition than decision tree.
What happens with the curve for random forests as the ensemble size grows?
The accuracy of both the trian set and test set increases accordingly.
What happens with the best observed test set accuracy as the ensemble size grows?
We tried with two sample so, but we observed that when the the ensemble size increases the accuracy of both the trianing and test set increases.
What happens with the training time as the ensemble size grows? 
Its accuracy approaches to 1. Therefore the model is good for both data sets.

# Task 3: Feature importances in random forest classifiers

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
rf = RandomForestClassifier(n_estimators = 100,
                           n_jobs = -1,
                           oob_score = True,
                           bootstrap = True,
                           random_state = 42)
rf.fit(X_train_encoded, Ytrain)
print('R^2 Training Score: {:.2f} \nOOB Score: {:.2f} \nR^2 Validation Score: {:.2f}'.format(rf.score(X_train_encoded, Ytrain), 
                                                                                            rf.oob_score_,
                                                                                          rf.score(X_test_encoded, Ytest)))

print("Accuracy:",metrics.accuracy_score(Y_new, Ytest))

#import pandas as pd
#clf1.fit(Xtrain,Ytrain)
#feature_imp = pd.Series(clf1.feature_importances_,index=data_training.feature_names).sort_values(ascending=False)
#feature_imp

R^2 Training Score: 1.00 
OOB Score: 0.85 
R^2 Validation Score: 0.85
Accuracy: 0.8092868988391376


In this taks we calculated the importance scores for individual features and acucracy metric score for the predicted data and the test data from the previous steps 